/**
 * Javascript object representing the different kind of notification
 * @type {{RACCOURCISSEMENT_OWNER: string, ACCEPTATION_DEMANDE_EMPRUNT: string, REFUS_DEMANDE_EMPRUNT: string, ANNULATION_RESERVATION_BORROWER: string, RESERVATION: string, REFUS_DEMANDE_RACOURCISSEMENT_BORROWER: string, MESSAGE: string, ANNULATION_RESERVATION_OWNER: string, RACCOURCISSEMENT_BORROWER: string, REFUS_DEMANDE_RACOURCISSEMENT_OWNER: string, ACCEPTATION_DEMANDE_RACOURCISSEMENT_BORROWER: string, SIGNALEMENT: string, ACCEPTATION_DEMANDE_RACOURCISSEMENT_OWNER: string, DEMANDE_RETOUR: string}}
 */
export const NOTIFICATION_STATE = {
    MESSAGE: "MESSAGE",
    SIGNALEMENT: "SIGNALEMENT",
    RESERVATION: "RESERVATION",
    RACCOURCISSEMENT_OWNER: "RACCOURCISSEMENT_OWNER",
    RACCOURCISSEMENT_BORROWER: "RACCOURCISSEMENT_BORROWER",
    ACCEPTATION_DEMANDE_EMPRUNT: "ACCEPTATION_DEMANDE_EMPRUNT",
    REFUS_DEMANDE_EMPRUNT: "REFUS_DEMANDE_EMPRUNT",
    ACCEPTATION_DEMANDE_RACOURCISSEMENT_OWNER: "ACCEPTATION_DEMANDE_RACOURCISSEMENT_OWNER",
    ACCEPTATION_DEMANDE_RACOURCISSEMENT_BORROWER: "ACCEPTATION_DEMANDE_RACOURCISSEMENT_BORROWER",
    REFUS_DEMANDE_RACOURCISSEMENT_OWNER: "REFUS_DEMANDE_RACOURCISSEMENT_OWNER",
    REFUS_DEMANDE_RACOURCISSEMENT_BORROWER: "REFUS_DEMANDE_RACOURCISSEMENT_BORROWER",
    ANNULATION_RESERVATION_OWNER :"ANNULATION_RESERVATION_OWNER",
    ANNULATION_RESERVATION_BORROWER :"ANNULATION_RESERVATION_BORROWER",
    DEMANDE_RETOUR :"DEMANDE_RETOUR"
}

/**
 * Used to know to what page redirect the user
 *
 * @param notification
 * @returns {string}
 */
export function notificationRedirectUrl(notification){
    let url;
     switch(notification.state){
         case NOTIFICATION_STATE.MESSAGE:
             url = "/home"
             break;
         case NOTIFICATION_STATE.SIGNALEMENT:
             url = "/home"
             break;
         case NOTIFICATION_STATE.RESERVATION:
             url="/dashboard/myloans/owner"
             break;
         case NOTIFICATION_STATE.RACCOURCISSEMENT_OWNER:
         case NOTIFICATION_STATE.ACCEPTATION_DEMANDE_RACOURCISSEMENT_OWNER:
         case NOTIFICATION_STATE.REFUS_DEMANDE_RACOURCISSEMENT_OWNER:
         case NOTIFICATION_STATE.ANNULATION_RESERVATION_OWNER:
             url="/dashboard/myloans/owner"
             break;
         case NOTIFICATION_STATE.ACCEPTATION_DEMANDE_EMPRUNT:
         case NOTIFICATION_STATE.REFUS_DEMANDE_EMPRUNT:
         case NOTIFICATION_STATE.RACCOURCISSEMENT_BORROWER:
         case NOTIFICATION_STATE.REFUS_DEMANDE_RACOURCISSEMENT_BORROWER:
         case NOTIFICATION_STATE.ACCEPTATION_DEMANDE_RACOURCISSEMENT_BORROWER:
         case NOTIFICATION_STATE.ANNULATION_RESERVATION_BORROWER:
         case NOTIFICATION_STATE.DEMANDE_RETOUR:
             url="/dashboard/myloans/borrower"
             break;
         default:
             url = "/home"
             break;
     }
     return url
}