export const NOTIFICATION_STATE = {
    MESSAGE: "MESSAGE",
    SIGNALEMENT: "SIGNALEMENT",
    RESERVATION: "RESERVATION",
    RACCOURCISSEMENT_OWNER: "RACCOURCISSEMENT_OWNER",
    RACCOURCISSEMENT_BORROWER: "RACCOURCISSEMENT_BORROWER",
    ACCEPTATION_DEMANDE_EMPRUNT: "ACCEPTATION_DEMANDE_EMPRUNT",
    REFUS_DEMANDE_EMPRUNT: "REFUS_DEMANDE_EMPRUNT",
    ACCEPTATION_DEMANDE_RACOURCISSEMENT_OWNER: "ACCEPTATION_DEMANDE_RACOURCISSEMENT_OWNER",
    ACCEPTATION_DEMANDE_RACOURCISSEMENT_BORROWER: "ACCEPTATION_DEMANDE_RACOURCISSEMENT_BORROWER",
    REFUS_DEMANDE_RACOURCISSEMENT_OWNER: "REFUS_DEMANDE_RACOURCISSEMENT_OWNER",
    REFUS_DEMANDE_RACOURCISSEMENT_BORROWER: "REFUS_DEMANDE_RACOURCISSEMENT_BORROWER",
    ANNULATION_RESERVATION_OWNER :"ANNULATION_RESERVATION_OWNER",
    ANNULATION_RESERVATION_BORROWER :"ANNULATION_RESERVATION_BORROWER"
}
export function notificationRedirectUrl(notification){
    let url;
     switch(notification.state){
         case NOTIFICATION_STATE.MESSAGE:
             // TODO que faire ?
             url = "/home"
             break;
         case NOTIFICATION_STATE.SIGNALEMENT:
             // TODO que faire ?
             url = "/home"
             break;
         case NOTIFICATION_STATE.RESERVATION:
             url="/dashboard/myloans/owner"
             break;
         case NOTIFICATION_STATE.RACCOURCISSEMENT_OWNER:
         case NOTIFICATION_STATE.ACCEPTATION_DEMANDE_RACOURCISSEMENT_OWNER:
         case NOTIFICATION_STATE.REFUS_DEMANDE_RACOURCISSEMENT_OWNER:
         case NOTIFICATION_STATE.ANNULATION_RESERVATION_OWNER:
             url="/dashboard/myloans/owner"
             break;
         case NOTIFICATION_STATE.ACCEPTATION_DEMANDE_EMPRUNT:
         case NOTIFICATION_STATE.REFUS_DEMANDE_EMPRUNT:
         case NOTIFICATION_STATE.RACCOURCISSEMENT_BORROWER:
         case NOTIFICATION_STATE.REFUS_DEMANDE_RACOURCISSEMENT_BORROWER:
         case NOTIFICATION_STATE.ACCEPTATION_DEMANDE_RACOURCISSEMENT_BORROWER:
         case NOTIFICATION_STATE.ANNULATION_RESERVATION_BORROWER:
             url="/dashboard/myloans/borrower"
             break;
         default:
             url = "/home"
             break;
     }
     return url
}